### PR TITLE
Heatmap border

### PR DESCRIPTION
**Pull request by lefty01**
Hi this would be a first version of adding --bbox switch to the tool. See the respective issue #7 
usage example:
./create_poster.py  --gpx-dir ~/Sport/strava/2016/ --year 2016 --title "on the run ..." --athlete "Andreas" --type heatmap --output poster-heat-bbox.svg --bbox 48.81583140218061  8.741218034088893 48.46361655741392 9.539988524403476

sample output without bbox:
http://exitzero.de/GpxTrackPoster/poster-heat1.svg
and with above bbox setting:
http://exitzero.de/GpxTrackPoster/poster-heat-bbox.svg

### CODE REVIEW

**Comment by lefty01** [comment]
well this actually doesn't look right *lol*
http://exitzero.de/GpxTrackPoster/schoenbuch-heat.svg
... so maybe ignore the merge request for now

**Comment by laufhannes** [comment]
Setting the boundaries and the view box does probably work, but all polylines are written into the svg, even if they are outside the box. This can cause images like yours and will bloat the svg file with polylines that are not shown anyway.

The tracks have to be filtered at some point. But what's with tracks that are partially contained in the view box? Could be hard to draw only the part of the polyline that's in the box.

**Comment by lefty01** [comment]
okay will rework and add filter while iterating over the track.polylines.

as for partial tracks ... maybe in that case we can still apply the boundaries to the box as in this patch but then include far less tracks.
So the filter function might not only include all tracks that are completely inside the specified bbox coords but also those only "touching" it. what do you think?

... closing this request for now.

**Comment by laufhannes** [comment]
It'd be nice to have some kind of a 'transition area', a small line of width 10 at each border, where tracks exceeding the bounding box fade out. But, honestly, I don't think that's possibly with svgwrite without tons of work.

My idea for filtering tracks would be:
 - calculate bounding box of a track
   - a) drop the track if the intersection of its bounding box and the requested bounding box is empty
   - b) fully include the track if its bounding box is a subset of the requested bounding box
   - c) loop through the track if parts of it (may) lie in the requested bounding box
     - if a point is within the requested bounding box, start constructing a polyline and append all following points that are within the bounding box
     - if a point is not within the requested bounding box, _finish_ the constructed polyline and go on

**Comment by flopp** [comment]
@laufhannes  Your idea sounds reasonable

**Pull request closed without merging**
