### PR TITLE
fix: #80

### PR DESCRIPTION
**Pull request by yihong0618**

### CODE REVIEW

**Comment by yihong0618** [comment]
@flopp  can we frozen the  `pylint` and `black` version?
Because my local seems work fine.
image

**Comment by flopp** [comment]
@yihong0618 thank you so much for the fix!

**Comment by flopp** [comment]
Do we still need  to freeze the pylint/black versions?

**Comment by yihong0618** [comment]
> Do we still need to freeze the pylint/black versions?

I think keep the lastest is fine.

**Pull request merged**
