### PR TITLE
Rename activity option

### PR DESCRIPTION
**Pull request by lowtower**
This PR renames the option "activity" to "activity_type" to be more clear and consistent with other options.
Additionally, this PR adds the filter "--activity-type" and other options to the README by running the script update-readme.

### CODE REVIEW

**Comment by flopp** [comment]
This could break some existing installations - maybe we should add an alias to be backwards compatible...

**Comment by flopp** [comment]
`args_parser.add_argument(["--activity-type", "--activity"], ...)` should work, I guess.

**Comment by lowtower** [comment]
To be honest, my initial PR was committed maybe a bit hastily.
With this PR, I want to correct some (in my eyes) messy inconsistencies, which is rather cosmetic than really necessary.
You are right, that this would break existing installations.
It's Your tool - You decide which way to go.
I am fine with both names as options (pushed with [commit f27d93e](https://github.com/flopp/GpxTrackPoster/pull/92/commits/f27d93e464c7851088a6d852ae3dc11115a468a3))

**Comment by flopp** [comment]
Thank you!

**Pull request merged**
