### PR TITLE
add: use-localtime command to local time show

### PR DESCRIPTION
**Pull request by yihong0618**
@flopp 
fix: #54 
and try to cache pip file in GitHub Action

### CODE REVIEW

**Comment by yihong0618** [comment]
why my `black` is different.....

**Comment by flopp** [comment]
Did you run `black --line-length 120` (e.g. via `make format`)?

**Comment by yihong0618** [comment]
> Did you run `black --line-length 120` (e.g. via `make format`)?

@flopp 

Yes.... Its the black version and pylint version problem...

can you add version in requirement? why the `pr` finish?

**Comment by yihong0618** [comment]
Finally!!!!

**Comment by yihong0618** [comment]
@flopp 
I only have +8 timezone...can you also take a test on `github` and others poster for the datetime ?

**Comment by flopp** [comment]
Works fine for my local +2 timezone!

@yihong0618, could you please squash the 9 commits into one? Then I can merge the PR...

**Comment by yihong0618** [comment]
@flopp done! Please check~

**Comment by flopp** [comment]
I will change the code to always adjust UTC timestamps to the timezone based on their lat/lng, as this seems to make perfect sense in general. => `--use-localtime` will also be removed...

**Comment by yihong0618** [comment]
> I will change the code to always adjust UTC timestamps to the timezone based on their lat/lng, as this seems to make perfect sense in general. => `--use-localtime` will also be removed...

I think you are right

**Comment by yihong0618** [comment]
@flopp  seems that still 9 commits, I used `rebase -i`  and local commits change to 1, but seems that it is also 9 commits here.

**Comment by yihong0618** [comment]
> Hm, ok. Doesn't really matter, I guess...

~Sorry for that.

**Comment by Djailla** [comment]
@yihong0618 when doing `git rebase -i` did you use `s` to squash commits ?

**Comment by yihong0618** [comment]
> @yihong0618 when doing `git rebase -i` did you use `s` to squash commits ?

yes...

**Comment by Djailla** [comment]
Then you end up with just one commit ?

And you can `git push -f`

**Comment by yihong0618** [comment]
> Then you end up with just one commit ?
> 
> And you can `git push -f`

I just push not -f. I think this may caused it, Thank you very much~

**Pull request merged**
