### PR TITLE
Circular drawer scale

### PR DESCRIPTION
**Pull request by lowtower**
Hello,

this PR provides a new cli argument for circular posters and lets the user scale the track length to a given value.

By now the radius of the circle is scaled to the maximum track length.
With this PR, the radius can be scaled to a given value, e.g.

My objective is to generate an animated gif over a period of time.
With a given radius the single posters would not "jump" in radius for every new calculated maximum length.

Hope, You like the change,
cheers,
LT

### CODE REVIEW

**Comment by lowtower** [comment]
I have added two examples to demonstrate what I mean
[today](https://github.com/lowtower/GpxTrackPoster/blob/circular_drawer_scale/examples/circular.gif)
[with fixed radius](https://github.com/lowtower/GpxTrackPoster/blob/circular_drawer_scale/examples/circular.fix.gif)

**Comment by flopp** [comment]
That's a nice addition. Thank you!

**Comment by lowtower** [comment]
Cool, thanks.
Just for Your information, I had added the example GIF files ro my repo before You merged - so they are in Your repo now as well.
You might want to delete or keep them - as You like.

**Comment by flopp** [comment]
Ok. I may remove them, because the file sizes are quite large.

**Comment by yihong0618** [comment]
@flopp @lowtower 

Can I ask how you generate the `gif` file?

My idea is we can generate `svg` file with animation that like you gif file, that would cool,

And add one  `arg --with animation`  user can choose with gif like yours or not.

**Comment by flopp** [comment]
@yihong0618 that would be a nice addition, I guess...

**Comment by lowtower** [comment]
@yihong0618 

I am working on a python script that either uses imagemagick if available or imageio.
In short, the script takes the gpx-dir and copies gpx-file after file to a temporary directory, generates a svg using GpxTrackPoster, generates a png and then combines all the separate png's to a single animated gif or video file.
It is already working but not tested and stable - thus not public avaliable.
Cheers,
LT

**Comment by yihong0618** [comment]
@lowtower 
Got it thanks.

**Pull request merged**
