### PR TITLE
add: from strava close #44

### LINKED ISSUE #44: Add Strava Import
Add a Strava import function (via `stravalib`).
It may be enough to fetch the activities overview which contains the actual activity tracks as stripped down "summary polylines".

### PR DESCRIPTION
**Pull request by yihong0618**
1. I add a new cache for strava. I think its simple and different from old gpx cache.
2. about time zone I used a tricky way

Please help me to review @flopp @Djailla 
Thank you very much.

### CODE REVIEW

**Comment by flopp** [comment]
Could you change the `--from-strava` option so that it takes the Strava authentication file as a parameter, e.g `--from-strava my-strava.json`? The current fixed file name `strava.json` that must exist in the current directory is not good, IMHO.

**Comment by yihong0618** [comment]
> Could you change the `--from-strava` option so that it takes the Strava authentication file as a parameter, e.g `--from-strava my-strava.json`? The current fixed file name `strava.json` that must exist in the current directory is not good, IMHO.

Thanks.
of course I will change it right now.

And are there other suggestions?

**Comment by yihong0618** [comment]
@flopp  
Done, learned that `git reabase -i` need to  `git push -f`

**Comment by flopp** [comment]
Ok, perfect. Thank you!
I will merge the PR and try it out...

**Comment by yihong0618** [comment]
Thank you.

**Pull request merged**
